name: Build Desktop App (Windows)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  checks: write

jobs:
  build:
    name: Build and Package Windows App
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.19.0'

      - name: Install dependencies
        run: |
          cd desktop
          flutter pub get

      - name: Build Windows Executable
        run: |
          cd desktop
          flutter build windows --release

      - name: Download Inno Setup
        run: |
          curl -L -o innosetup.exe https://jrsoftware.org/download.php/is.exe
          Start-Process -Wait -FilePath innosetup.exe -ArgumentList '/VERYSILENT', '/SUPPRESSMSGBOXES', '/NORESTART', '/SP-'

      - name: Create Installer with Inno Setup
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installers/installer_script.iss
        working-directory: desktop

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v3
        with:
          name: Indoor Tracking Installer
          path: desktop/installers/Output/IndoorTrackingInstaller.exe
