name: Build Desktop App (Windows)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  checks: write

jobs:
  build:
    name: Build and Package Windows App
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.19.0'

      - name: Install dependencies
        run: |
          cd desktop
          flutter pub get

      - name: Build Windows Executable
        run: |
          cd desktop
          flutter build windows --release

      - name: Download Inno Setup Portable
        run: |
          curl -L -o innosetup.zip https://www.jrsoftware.org/download.php/is.zip
          tar -xf innosetup.zip -C innosetup

      - name: Create Installer with Inno Setup
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installers/installer_script.iss
        working-directory: desktop

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v3
        with:
          name: Indoor Tracking Installer
          path: desktop/installers/Output/IndoorTrackingInstaller.exe
