name: Build Desktop App (Windows)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  checks: write

jobs:
  build:
    name: Build and Package Windows App
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.19.0'

      - name: Install dependencies
        run: |
          cd desktop
          flutter pub get

      - name: Build Windows Executable
        run: |
          cd desktop
          flutter build windows --release

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: desktop/IndoorTracking.iss
          options: /O+


      - name: Upload Windows Installer
        uses: actions/upload-artifact@v3
        with:
          name: Indoor Tracking Installer
          path: desktop/Output/IndoorTracking.exe
