name: Build Desktop App (Windows)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  checks: write

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    - name: Install dependencies
      run: |
        cd desktop
        flutter pub get

    - name: Run tests
      run: |
        cd desktop
        flutter test --machine > tests.output

    - name: Test Reporter
      uses: dorny/test-reporter@v1.9.1
      if: always()
      with:
        name: Flutter Tests
        path: desktop/tests.output
        reporter: flutter-json
        fail-on-error: false

  build:
    name: Build and Package Windows App
    runs-on: windows-latest
    needs: tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.19.0'

      - name: Install dependencies
        run: |
          cd desktop
          flutter pub get

      - name: Build Windows Executable
        run: |
          cd desktop
          flutter build windows --release

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: desktop/IndoorTracking.iss
          options: /O+


      - name: Upload Windows Installer
        uses: actions/upload-artifact@v3
        with:
          name: Indoor Tracking Installer
          path: desktop/Output/IndoorTracking.exe
