name: desktop
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.4.2
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0
  shared_preferences: ^2.0.6
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.1
  shimmer: ^2.0.0
  screen_retriever: ^0.1.9
  file_picker: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.0.0
  junitreport: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/